---
title: "HW4MMendoza"
format: pdf
editor: visual
---

# Preliminary Requirements

```{r}
# Libraries
library(emmeans)

# Copy code from Heart/Lung experiment
# Create dataframe
rpm <- c(150, 50, 50, 75, 150, 150, 100, 100, 100, 125, 
         100, 50, 125, 150, 100, 75, 50, 50, 150, 75)
level <- factor(c(5, 1, 1, 2, 5, 5, 3, 3, 3, 4, 
                  3, 1, 4, 5, 3, 2, 1, 1, 5, 2))
liters_minute <- c(3.540, 1.158, 1.128, 1.686, 3.480, 3.510, 
                   2.328, 2.340, 2.298, 2.982, 2.328, 1.140, 
                   2.868, 3.504, 2.340, 1.740, 1.122, 1.128, 
                   3.612, 1.740)

hl_data <- data.frame(rpm, level, liters_minute)
print(hl_data)


#aov to create anova table
aov_rslt <- aov(liters_minute ~ level, hl_data)


#anova to create anova table
anova_rslt <- anova(aov_rslt)
```

# Q1

```{r}
#Investigate what you can extract from "aov_rslt" object
names(aov_rslt)

#Investigate what you can extract from "anova_rslt" object
names(anova_rslt)

# Use EMMEANS to Calculate the estimated marginal means
rpm_emms <- emmeans(aov_rslt, ~ level)

# Define the custom contrast vector 
contrast1 <- contrast(rpm_emms, method = list("r5 minus r1" = c(-1, 0, 0, 0, 1)))

# Extract the test results along with the 95% confidence interval
summary(contrast1, infer = TRUE, level = 0.95)

# estimate = 2.39
# standard error = 0.0236
#𝑝-value = <0.0001
# confidence interval = [2.34, 2.44]
```

# Q2

```{r}
# create contrast list
contrasts <- list(
  "r2_minus_r1" = c(-1,  1,  0,  0,  0),
  "r5_minus_r4" = c( 0,  0,  0, -1,  1)
)

# Contrast Results
contrast2 <- contrast(rpm_emms, method = contrasts)
print(contrast2)

# Test Null hypothosis
test_rslt <- test(contrast2, joint = TRUE)
print(test_rslt)

# use VCOV 
vcov_rslt <- vcov(contrast2)
print(vcov_rslt)
```

# Q3

```{r}
# Create turkey Pairwise Comparison
contrast3 <- contrast(rpm_emms,method="tukey",infer=c(T,T))
contrast3

```
